server:
  port: 8888
  error:
    include-message: always
    include-stacktrace: never

#logging:
#  level:
#    root: DEBUG

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: mdm-registry-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      username: ${REDIS_USER:default}
      password: ${REDIS_PASSWORD:}
  kafka:
    bootstrap-servers: ${KAFKA_URL_LIST:localhost:9092}
    producer:
      acks: ${KAFKA_PRODUCER_ACKS:1}
      retries: ${KAFKA_PRODUCER_RETRIES:2}
    consumer:
      auto-offset-reset: ${KAFKA_CONSUMER_AUTO_OFFSET_RESET:earliest}
      group-id: ${ENVIRONMENT_PREFIX:local}-${spring.application.name}
      properties:
        spring:
          json:
            trusted: # Данное свойство разрешает десереализацию всех классов.
              packages: '*'

mdm:
  application:
    name: ${spring.application.name}
    description: Сервис "Реестр микросервисов"
    version: local
    route:
      uri: http://localhost:${server.port}
      predicates:
        - Path=/mdm-registry-service/**
      filters:
        - StripPrefix=1
    controllers:
      - ru.mdm.registry.rest
      - ru.mdm.registry.controller